### ISSUE TITLE
windowManager.getCurrent() - Doesn't return a window.

### ISSUE THREAD

**Issue by Bossehasse** [TamkeenLMS/electron-window-manager#25]
```
Uncaught Error: Could not call remote function 'emit'. Check that the function signature is correct. Underlying error: Cannot read property 'id' of undefined
Error: Could not call remote function 'emit'. Check that the function signature is correct. Underlying error: Cannot read property 'id' of undefined
    at callFunction (/Users/Bossehasse/projects/vagranti_testing/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:235:11)
    at EventEmitter.<anonymous> (/Users/Bossehasse/projects/vagranti_testing/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:342:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/Users/Bossehasse/projects/vagranti_testing/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

The path to the ID is wrong: 
```javascript
'getCurrent': function(){
            var thisWindow = BrowserWindow.getFocusedWindow();
            if(!thisWindow) return false;

            // return this.getById(thisWindow.object.id); <--- Original
            return this.getById(thisWindow.id); // Now it works!
        },
```

**Comment by jbeatty80** [comment]
Seconding this, plus it would be nice to have show/hide mapped as well.

**Comment by dmtask** [comment]
I have the same or the like Problem.

I became the following error:
```
Uncaught Exception:
TypeError: Cannot read property 'id' of undefined
    at Object.getCurrent (/node_modules/electron-window-manager/index.js:923:50)
    at Object.emit (/node_modules/electron-window-manager/index.js:1095:48)
    at storage.set (/src/settingsWindow.js:39:34)
    at /node_modules/async/dist/async.js:356:16
    at nextTask (/node_modules/async/dist/async.js:5057:29)
    at /node_modules/async/dist/async.js:5064:13
    at apply (/node_modules/async/dist/async.js:21:25)
    at /node_modules/async/dist/async.js:56:12
    at /node_modules/async/dist/async.js:840:16
    at /node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Is this an error in the electron-window-manager lib?

**Comment by TamkeenLMS** [comment]
Fixed the code. Check if it's working now.

**Comment by dmtask** [comment]
Yes it works :)

Thank you.

**Comment by dmtask** [comment]
When is the new version available?

**Comment by TamkeenLMS** [comment]
We are sorry we aren't focusing more on this package, but we are so busy right now. I myself cannot promise a new release, but it will probably happen eventually.
